### ISSUE TITLE
TalonSRX Usage

### ISSUE THREAD

**Issue by roshanr10** [first-team-58/2018-PowerUp#1]
Just came across this when I was browsing through my GitHub feed.... it seems as though you've created `TalonSRX` objects as masters and `Talon` objects as followers; `Talon` objects are PWM only, and are meant for the older TalonSR motor controllers.

https://github.com/first-team-58/2018-PowerUp/blob/b18e3091cbbe4a7c3083f36a74f54c9f87c31e1b/src/org/usfirst/frc/team58/robot/subsystems/DriveTrain.java#L18

Also, would recommend using `WPI_TalonSRX` over `TalonSRX` for easier integration into builtin WPI lib drivetrain code. The latter doesn't implement the `SpeedController` interface.

**Comment by tylermhansen** [comment]
Thanks for pointing that out! We hadn't had a chance to fully explore the Phoenix docs.

**Comment by roshanr10** [comment]
hey again, nice fixes, but wouldn't recommend using CAN IDs multiple times, easier to mess up. Try `m_RightSlave.follow(m_FrontRightMotor);` as opposed to this:

https://github.com/first-team-58/2018-PowerUp/blob/f075a167024eb4213512d6c623262f1770dce965/src/org/usfirst/frc/team58/robot/subsystems/DriveTrain.java#L28

If you have any questions about Phoenix, feel free to reach out to me, I've done some extensive research into em.

**Comment by tylermhansen** [comment]
Awesome, thanks!
